version: '3.8'

services:
  ssq:
    build: .
    container_name: ssq-app
    restart: always
    ports:
      - "51168:51168"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production
    volumes:
      - ./logs:/app/logs 